### PR TITLE
Added field-width token

### PR DESCRIPTION
**Pull request by GarthDB**
## Description

Added `field-width` token.

## Related Issue

- [DNA-1239](https://jira.corp.adobe.com/browse/DNA-1239)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by GarthDB** [comment]
<details><summary><strong>Tokens added (1)</strong></summary>

  - `field-width`
</details>

**Review by misterbrownlee — APPROVED** [review]
yes. thanks.

**Pull request merged**
