### PR TITLE
feat: rename meter-thickness-medium; closes DNA-1224

### PR DESCRIPTION
**Pull request by misterbrownlee**
## Description
Renames meter-thickness-medium to meter-thickness large

## Related Issue
DNA-1224

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by misterbrownlee** [comment]
@GarthDB also please fix my commit message typo when you merge!

**Review by GarthDB — APPROVED** [review]

**Pull request merged**
