### PR TITLE
feat(tokens): update color token values

### PR DESCRIPTION
**Pull request by karstens**
## Description

Updated existing non-gray S2 palette colors, in light and dark:
- blue
- green
- orange
- red
- celery
- chartreuse
- cyan
- fuchsia
- indigo
- magenta
- purple
- seafoam
- yellow

## Motivation and context

This update addresses several improvements:
- fuchsia, seafoam: all values shifted to make room for new colors, pink and turquoise
- all other colors: certain values were updated to address accessibility contrast requirements against Spectrum 2 background layer colors

## Related issue

[SDS-13195](https://jira.corp.adobe.com/browse/SDS-13195)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by karstens** [comment]
@GarthDB @mrcjhicks This is my first PR. I created it via the diff-script based on the changes in the tokens-studio-data repo [here](https://github.com/adobe/spectrum-tokens-studio-data/pull/9). I also added a changeset, but not sure, if it is a patch or minor change. I did not see a pre-patch option in the changeset cli. Please let me know, if this is okay. Thanks Frank

**Comment by GarthDB** [comment]
The `pre` is all handled in the [pre.json file](https://github.com/adobe/spectrum-tokens/blob/beta/.changeset/pre.json). We can just keep adding more changeset files until we need to graduate to latest/main. I did edit the changeset to include the design motivation and token diff from the last beta release. If you want to do this locally you can run `moon run tokens:generateDiffResult -- beta` which will fetch the latest `beta` release from npm and compare it to the local files.

**Comment by GarthDB** [comment]
## Run report for [16c957ca](https://github.com/adobe/spectrum-tokens/commit/16c957cac8c468b36ecb0ec8bcb8428a645eea81)
Total time: 51.6s | Comparison time: 54.1s | Estimated savings: 2.5s (4.6% faster)
|     | Action | Time | Status | Info |
| :-: | :----- | ---: | :----- | :--- |
| 🟩 | `SyncWorkspace` | 0ms | Passed |  |
| 🟩 | `SetupNodeTool(18.13.0)` | 5s | Passed |  |
| 🟩 | `InstallNodeDeps(18.13.0)` | 6.9s | Passed |  |
| 🟩 | `SyncNodeProject(visualizer)` | 0.2ms | Passed |  |
| 🟩 | `SyncNodeProject(tokens)` | 0.3ms | Passed |  |
| 🟩 | `SyncNodeProject(site)` | 0.2ms | Passed |  |
| 🟩 | `RunTask(visualizer:typescript)` | 2.4s | Passed |  |
| 🟩 | `RunTask(tokens:buildTokens)` | 11.9s | Passed |  |
| 🟩 | `RunTask(tokens:buildManifest)` | 327.8ms | Passed |  |
| 🟩 | `RunTask(site:copySchema)` | 119.1ms | Passed |  |
| 🟩 | `RunTask(visualizer:build)` | 3.9s | Passed |  |
| 🟩 | `RunTask(tokens:build)` | 1.8s | Passed |  |
| 🟩 | `RunTask(tokens:generateDiffResult)` | 3.5s | Passed |  |
| 🟩 | `RunTask(tokens:test)` | 1.8s | Passed |  |
| 🟩 | `RunTask(site:build)` | 23s | Passed |  |
| 🟩 | `RunTask(site:clean)` | 84.8ms | Passed |  |
| 🟩 | `RunTask(site:export)` | 807ms | Passed |  |

<details><summary><strong>Touched files</strong></summary><div>

```
.changeset/good-peas-mix.md
.changeset/happy-students-vanish.md
.changeset/lemon-dragons-raise.md
.changeset/neat-balloons-rhyme.md
.changeset/pre.json
.changeset/slimy-emus-enjoy.md
.changeset/strange-rings-love.md
.changeset/warm-experts-beg.md
.github/workflows/deploy-docs.yml
.github/workflows/release.yml
.moon/toolchain.yml
.moon/workspace.yml
package-lock.json
package.json
packages/tokens/CHANGELOG.md
packages/tokens/package.json
packages/tokens/src/color-aliases.json
packages/tokens/src/color-component.json
packages/tokens/src/color-palette.json
packages/tokens/src/icons.json
packages/tokens/src/layout-component.json
packages/tokens/src/layout.json
packages/tokens/src/semantic-color-palette.json
packages/tokens/src/typography.json
packages/tokens/tasks/diff.js
pnpm-lock.yaml
pnpm-workspace.yaml
tools/transform-tokens-json/README.md
tools/transform-tokens-json/moon.yml
tools/transform-tokens-json/package.json
tools/transform-tokens-json/src/lib/shared.js
tools/transform-tokens-json/src/merge-dark-darkest.js
tools/transform-tokens-json/src/merge-spectrum-express.js
tools/transform-tokens-json/test/index.test.js
```

</div></details>

**Comment by karstens** [comment]
@GarthDB Ah, so I missed running the second diff script for spectrum-tokens. Got it! 💡 Thank you!

**Pull request merged**
