### PR TITLE
Fixes and formatting

### PR DESCRIPTION
**Pull request by GarthDB**
## Description

* added neutral-background-color-selected tokens
* added missing color-slider color tokens:
  * `color-slider-border-color`
  * `color-slider-border-opacity`
* fixed typo in token name:
  * renamed `color-wheel-area-margin` to `color-wheel-color-area-margin`
* reorganized tokens to align with Excel document better for easier comparisons

## Related Issue

* [DNA-1233](https://jira.corp.adobe.com/browse/DNA-1233)
* [DNA-1238](https://jira.corp.adobe.com/browse/DNA-1238)
* [DNA-1235](https://jira.corp.adobe.com/browse/DNA-1235)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by misterbrownlee — APPROVED** [review]
This looks good, thanks!

**Comment by mfal** [comment]
@GarthDB The MR was quite a long time ago, but I'll give it a try anyway. Maybe you can give me a good hint.

Briefly about the background of my question. I am currently educating myself in the area of design systems and I am using Spectrum as a well done example. I'm currently looking into building and using Spectrum's design tokens, and in the process I came across the following question:

Why does the eventual [Slider Component](https://opensource.adobe.com/spectrum-css/slider.html#filled-offset) directly uses the gray colors (`gray-300` and `gray-700`) for the background of the (filled) track, instead of any existing color alias?  I mean, are there no intervening design decisions with these colors that are reflected in the alias tokens? This decision might even be applicable to the Switch.

Thanks for your answer!

**Pull request merged**
