### PR TITLE
Token Typo

### PR DESCRIPTION
**Pull request by GarthDB**
## Description

Tokens were mistakenly named in the excel file; this pr fixes it but adds aliases for the old names with deprecation metadata until the next major release.

## Related Issue

https://jira.corp.adobe.com/browse/DNA-1278

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by GarthDB** [comment]
Token Diff:

<details><summary>Tokens Added (3)</summary>

 - `alert-banner-bottom-to-text`
 - `alert-banner-top-to-text`
 - `alert-banner-top-to-workflow-icon`

</details>
<details><summary>Token Values Updated (3)</summary>

 - `alert-banner-to-bottom-text` (switched to alias replacement token)
 - `alert-banner-to-top-text` (switched to alias replacement token)
 - `alert-banner-to-top-workflow-icon` (switched to alias replacement token)

</details>

**Review by misterbrownlee — APPROVED** [review]
Yes. Thanks!

**Pull request merged**
