### PR TITLE
Color Loupe and New Card Tokens

### PR DESCRIPTION
**Pull request by GarthDB**
## Description

* Added new tokens
* Fixed a token name typo
* basic cleanup of a couple files

## Related Issue

- [DNA-1250](https://jira.corp.adobe.com/browse/DNA-1250) New Cards tokens
- [DNA-1249](https://jira.corp.adobe.com/browse/DNA-1249) Color loupe tokens

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by GarthDB** [comment]
<details><summary><h3>Tokens added (16):<h3></summary>

  - `card-minimum-width`
  - `card-preview-minimum-height`
  - `card-selection-background-color`
  - `card-selection-background-color-opacity`
  - `card-selection-background-size`
  - `color-loupe-bottom-to-color-handle`
  - `color-loupe-drop-shadow-blur`
  - `color-loupe-drop-shadow-color`
  - `color-loupe-drop-shadow-y`
  - `color-loupe-height`
  - `color-loupe-inner-border`
  - `color-loupe-inner-border-width`
  - `color-loupe-outer-border`
  - `color-loupe-outer-border-width`
  - `color-loupe-width`
</details>
<details><summary><h3>Tokens renamed (1):</h3></summary>

  - `detail-margin-top-mulitplier` -> `detail-margin-top-multiplier`
</details>

**Comment by misterbrownlee** [comment]
This looks good, thanks. The linting is nice.

**Review by misterbrownlee — APPROVED** [review]

**Pull request merged**
